config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :gyms do
    resources :comments
    member do
      put "like", to: "gyms#upvote"
      put "dislike", to: "gyms#downvote"
    end
  end

  root 'gyms#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :gym
end

app/models/gym.rb
class Gym < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user

  acts_as_votable

  geocoded_by :address
  after_validation :geocode

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :gyms,    dependent: :destroy
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @gym = Gym.find(params[:gym_id])
    @comment = Comment.create(params[:comment].permit(:body))
    @comment.user_id = current_user.id
    @comment.user_email = current_user.email
    @comment.gym_id = @gym.id

    if @comment.save
      redirect_to gym_path(@gym)
    else
      render 'new'
    end
  end
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  def index
    @gyms = Gym.all.order('created_at DESC')

    @hash = Gmaps4rails.build_markers(@gyms) do |gym, marker|
      marker.lat gym.latitude
     
      marker.lng gym.longitude
      marker.infowindow "#{gym.name} <br> #{gym.owner} <br> Hours: #{gym.hours} <br> #{gym.website}"
    end
  end

  def new
    @gym = Gym.new
  end

  def create
    @gym = Gym.new(gym_params)

		if @gym.save
			redirect_to @gym
		else
			render 'new'
		end
  end

  def show
    @gym = Gym.find(params[:id])

    @hash = Gmaps4rails.build_markers(@gym) do |gym, marker|
      marker.lat gym.latitude
      marker.lng gym.longitude
    end
  end

  def edit
    @gym = Gym.find(params[:id])
  end

  def update
    @gym = Gym.find(params[:id])

		if @gym.update(params[:gym].permit(:name, :owner, :hours, :fb_page, :tw_page, :ins_page, :website, :address, :latitude, :longitude))
			redirect_to @gym
		else
			render 'edit'
		end
  end

  def destroy
    @gym = Gym.find(params[:id])
		@gym.destroy

		redirect_to gyms_path
  end

  def upvote
    @gym = Gym.find(params[:id])
    @gym.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @gym = Gym.find(params[:id])
    @gym.downvote_by current_user
    redirect_to :back
  end

  def score
    @score = self.get_upvotes.size - self.get_downvotes.size
  end

  private

  def gym_params
    params.require(:gym).permit(:name, :owner, :hours, :fb_page, :tw_page, :ins_page, :website, :address, :latitude, :longitude)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/views/gyms/_form.html.erb
<%= form_for @gym do |f| %>
	<% if @gym.errors.any? %>
		<div id="errors">
			<p><%= pluralize(@gym.errors.count, "error") %></p>
			<ul>
				<% @gym.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%= f.label :name %><br>
	<%= f.text_field :name %><br>
	<br>
  <%= f.label :owner %><br>
	<%= f.text_field :owner %><br>
	<br>
  <%= f.label :hours, "Hours, for example 8:00-20:00" %><br>
    <%= f.text_field :hours %><br>
    <br>
  <%= f.label :website %><br>
	<%= f.text_field :website %><br>
	<br>
  <%= f.label :fb_page %><br>
	<%= f.text_field :fb_page %><br>
	<br>
	<%= f.label :address, "Address, for example: Nowoursynowska 166 Warszawa Polska"%><br>
	<%= f.text_field :address %><br>
	<br>
  <%= f.label :tw_page %><br>
	<%= f.text_field :tw_page %><br>
	<br>
  <%= f.label :ins_page %><br>
	<%= f.text_field :ins_page %><br>
	<br>
	<%= f.submit "Add new gym", class: "btn btn-default new_gym_btn" %>
<% end %>

app/views/gyms/edit.html.erb
<div class="row edit_gym">
    <div class="col-sm-6 col-sm-offset-3 col-xs-8 col-xs-offset-2">
        <h1>Edit Gym</h1>
        
        <%= render 'form' %>
    </div>
</div>

app/views/gyms/index.html.erb
<script src="//maps.google.com/maps/api/js?key={}"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<h1>Find gym in your neighbourhood</h1>

<div class="row ranking">

  <% @gyms.each do |gym| %>
    <div class="gym_panel">
      <div class="col-sm-4 col-xs-7">
        <%= link_to gym.name, gym %>
      </div>
      <div class="col-sm-3 index_website">
        <%= link_to gym.website, "http://#{gym.website}", target: "_blank" %>
      </div>
      <div class="col-sm-1 index_icon">
        <%= link_to '<i class="fa fa-facebook"></i>'.html_safe, "http://#{gym.fb_page}", target: "_blank"%>
      </div>
      <div class="col-sm-1 index_icon">
        <%= link_to '<i class="fa fa-twitter"></i>'.html_safe, "http://#{gym.tw_page}", target: "_blank"%>
      </div>
      <div class="col-sm-1 index_icon">
        <%= link_to '<i class="fa fa-instagram"></i>'.html_safe, "http://#{gym.ins_page}", target: "_blank"%>
      </div>
      <div class="col-sm-2 col-xs-5 vote">
        <%= gym.get_upvotes.size %><%= fa_icon "thumbs-up", class:"vote"  %>
      </div>
    </div>
    <div class="line"></div>
  <% end %>

</div>

<div class="row map_wrapper">
  <div id="map"></div>
</div>

<script type="text/javascript">
  var mapStyle = [{"featureType":"all","elementType":"labels.text.fill","stylers":[{"color":"#ffffff"}]},{"featureType":"all","elementType":"labels.text.stroke","stylers":[{"color":"#000000"},{"lightness":13}]},{"featureType":"administrative","elementType":"geometry.fill","stylers":[{"color":"#000000"}]},{"featureType":"administrative","elementType":"geometry.stroke","stylers":[{"color":"#144b53"},{"lightness":14},{"weight":1.4}]},{"featureType":"landscape","elementType":"all","stylers":[{"color":"#08304b"}]},{"featureType":"poi","elementType":"geometry","stylers":[{"color":"#0c4152"},{"lightness":5}]},{"featureType":"road.highway","elementType":"geometry.fill","stylers":[{"color":"#000000"}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#0b434f"},{"lightness":25}]},{"featureType":"road.arterial","elementType":"geometry.fill","stylers":[{"color":"#000000"}]},{"featureType":"road.arterial","elementType":"geometry.stroke","stylers":[{"color":"#0b3d51"},{"lightness":16}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#000000"}]},{"featureType":"transit","elementType":"all","stylers":[{"color":"#146474"}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#021019"}]}];

  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {styles:    mapStyle}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  });
</script>

app/views/gyms/new.html.erb
<div class="row new_gym">
    <div class="col-sm-6 col-sm-offset-3 col-xs-8 col-xs-offset-2">
        <h1>New gym</h1>

        <%= render 'form' %>
    </div>
</div>

app/views/gyms/show.html.erb
<script src="//maps.google.com/maps/api/js?key={}"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<p id="notice"><%= notice %></p>
<div class="row show">
  <div class="col-sm-6 show_map" id="map_show_page" style="height: 300px;"></div>
  <div class="col-sm-6 gym_details">
    <h1><%= @gym.name %></h1>

    <% if user_signed_in? %>
     <%= link_to "Edit", edit_gym_path(@gym), class:"btn btn-default" %>
     <%= link_to "Delete", gym_path(@gym), method: :delete, data: { confirm: "Are you sure?"}, class:"btn btn-default" %>
    <% end %>

    <h4>Owner: <%= @gym.owner %></h4>
    <h4>Address: <%= @gym.address %></h4>
    <h4>Hours: <%= @gym.hours %></h4>
    <h4><%= link_to @gym.website, "http://#{@gym.website}", target: "_blank" %></h4>

    <div class="social_icons">
      <%= link_to '<i class="fa fa-facebook"></i>'.html_safe, "http://#{@gym.fb_page}", target: "_blank"%>
      <%= link_to '<i class="fa fa-twitter"></i>'.html_safe, "http://#{@gym.tw_page}", target: "_blank"%>
      <%= link_to '<i class="fa fa-instagram"></i>'.html_safe, "http://#{@gym.ins_page}", target: "_blank"%>
    </div>

    <h3>Vote:</h3>
    <h2 class="vote_h2"><%= @gym.get_upvotes.size %></h2>
    <%= link_to like_gym_path(@gym), method: :put do %>
      <%= fa_icon "thumbs-up", class:"vote"  %>
    <% end %>

    <h2 class="vote_h2"><%= @gym.get_downvotes.size %></h2>
    <%= link_to dislike_gym_path(@gym), method: :put do %>
      <%= fa_icon "thumbs-down", class:"vote" %>
    <% end %>
  </div>
</div>
<div class="comment_box">
  <h2>Add a comment:</h2>
  <%= form_for([@gym, @gym.comments.build]) do |f| %>
    <div class="field">
      <%= f.text_area :body, class:"comment_body", placeholder: "Write a comment..." %>
    </div>
    <div class="actions">
      <%= f.submit "Write Comment", class:"btn btn-default comment_btn" %>
    </div>
  <% end %>
</div>

<div class="comments">
  <h2>Comments:</h2>
  <% @gym.comments.each do |comment| %>
      <h3><%= comment.user_email%></h3>
      <h6><%= comment.created_at %></h6>
      <h4><%= comment.body %></h4>
  <% end %>
</div>

<script type="text/javascript">
  var mapStyle = [{"featureType":"all","elementType":"labels.text.fill","stylers":[{"color":"#ffffff"}]},{"featureType":"all","elementType":"labels.text.stroke","stylers":[{"color":"#000000"},{"lightness":13}]},{"featureType":"administrative","elementType":"geometry.fill","stylers":[{"color":"#000000"}]},{"featureType":"administrative","elementType":"geometry.stroke","stylers":[{"color":"#144b53"},{"lightness":14},{"weight":1.4}]},{"featureType":"landscape","elementType":"all","stylers":[{"color":"#08304b"}]},{"featureType":"poi","elementType":"geometry","stylers":[{"color":"#0c4152"},{"lightness":5}]},{"featureType":"road.highway","elementType":"geometry.fill","stylers":[{"color":"#000000"}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#0b434f"},{"lightness":25}]},{"featureType":"road.arterial","elementType":"geometry.fill","stylers":[{"color":"#000000"}]},{"featureType":"road.arterial","elementType":"geometry.stroke","stylers":[{"color":"#0b3d51"},{"lightness":16}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#000000"}]},{"featureType":"transit","elementType":"all","stylers":[{"color":"#146474"}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#021019"}]}];

  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {styles:    mapStyle}, internal: {id: 'map_show_page'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  });
</script>

app/views/layouts/_menu.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "FitRank", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">

      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Add gym", new_gym_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete  %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
    </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fitrank</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/menu' %>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <div class="container">
    <%= yield %>

    <div class="row footer">
      <h5>@2016 FitRank. All rights reserved.</h5>
      <h6>Created by <a href="https://github.com/RadoszSzymon" target="_blank">Radosz Szymon</a></h6>
    </div>
  </div>

</body>
</html>